### ISSUE TITLE
HACS?

### ISSUE THREAD

**Issue by buddhra** [pnbruckner/ha-composite-tracker#13]
I'm looking for composite-tracker in HACS and I'm not finding it. Did something change there?

**Comment by pnbruckner** [comment]
It's never been an official part of HACS as far as I know, although I believe it is compatible with HACS. You have to add it as a custom repository. See the HACS docs. I don't know how to do that.

**Comment by jaburges** [comment]
@pnbruckner you have referenced HACS but you don't use HACS. Can you either follow the guidance to integrate or remove the HACS part (its pretty easy to be part of it).

just need to update the [HACS repo list](https://github.com/hacs/default/blob/master/integration)
add a hacs.json (manifest)
info.md (like a readme)
[here is an example](https://github.com/arjenvrh/audi_connect_ha)

**Comment by jaburges** [comment]
I created 2 PRs for the hacs.json and info.md
here is some more guidance: https://hacs.xyz/docs/publish/start
I cant create the HACS PR until these files are merged as need to test the repo manually before it gets added to HACS

**Comment by pnbruckner** [comment]
@jaburges 

I directly supported HACS, and it's predecessor `custom_updater`, for quite a while, with all of my custom integrations, but gave up a long time ago because they were constantly moving targets (and seem to still be.) I have no desire to keep up with it. As far as I know my custom integrations are still compatible with it (that's what people tell me), but if that is no longer the case then I don't plan to do anything about it.

**Comment by vakilando** [comment]
>...but if that is no longer the case then I don't plan to do anything about it.

ok, that's your choice. 
I'll install the composite-tracker manually then because it is NOT compatible with HACS.
Trying to add it as a custom repository results in: 

> An error occurred while processing
Exception: HacsException
Message: Repostitory structure for 2.1.2 is not compliant
Could not add this repository, make sure it is compliant with HACS.

As @jaburges said you should remove the HACS part then.

**Comment by pnbruckner** [comment]
> As @jaburges said you should remove the HACS part then.

Will do.

**Comment by pnbruckner** [comment]
Done.
