### ISSUE TITLE
Stop Working from 0.113.3 

### ISSUE THREAD

**Issue by Gobolin80** [pnbruckner/ha-composite-tracker#22]
Hi,
I have your custom component on my Raspbeery Pi from many time and I never had problems.
Sunday 2 August I installed version 0.113.3 and it stop to work.
In particular I have this settings:

    platform: composite
    name: key_tracker_enrico
    time_as: local
    entity_id:
      - binary_sensor.key_tracker_enrico #generato da ESP Home
    interval_seconds: 10
    consider_home: 600

Binary sensor is working fine, but device tracker never follow him.

If I look in Developer tools i see that the type is "gps" but it's false.
In real it's a binary sensor:

`
source_type: gps 
latitude: xx.yyyyyyyy
longitude: zz.wwwwww 
gps_accuracy: 0 
entity_id: binary_sensor.key_tracker_enrico 
last_entity_id: binary_sensor.key_tracker_enrico 
friendly_name: key tracker enrico
`

Thanks for your work

**Comment by pnbruckner** [comment]
I'm using it with 0.113.3 and it works ok for me. But I'm not using it with a binary sensor.

When you say it doesn't work, can you elaborate on that? Also are you seeing any warnings or errors?

> If I look in Developer tools i see that the type is "gps" but it's false.
In real it's a binary sensor

The composite entity is a device tracker, and must use existing device tracker source types. So that is expected.

Please configure your logger this way:
```yaml
logger:
  default: info
  logs:
    custom_components.composite: debug
```
Then restart HA. After it is running for a while, look in home-assistant.log for messages labeled `custom_components.composite.device_tracker`. That should give you more information about how the composite tracker is responding to the binary sensor.

**Comment by Gobolin80** [comment]
Thank you @pnbruckner  for your fast replay.
Well ... I'll try to explain what i'm seeing, because it's not simple :)
While I waited for you answer  I understood this:

On the same day when I upgrade to 0.113.3 i enabled "zone".
I setted the parameter 'passive = true' so **I disabled ALL my gps device tracker**.
The first error was mine :(

The strangeness comes now: I have the following 3 composite device tracker and ALL of these reads a binary sensor (from ESP Home device).

I post here the log:
-----------------------------------------------------------------
2020-08-04 15:16:13 DEBUG (SyncWorker_4) [custom_components.composite.device_tracker] Updating device_tracker.key_tracker_enrico **from binary_sensor.key_tracker_enrico**

2020-08-04 15:16:13 DEBUG (SyncWorker_2) [custom_components.composite.device_tracker] Updating device_tracker.enrico_on_bed **from binary_sensor.enrico_sleep**

2020-08-04 15:16:13 DEBUG (SyncWorker_2) [custom_components.composite.device_tracker] Updating device_tracker.erica_on_bed **from binary_sensor.erica_sleep**
-----------------------------------------------------------------
The last two works fine, while the first  (key_tracker_enrico) stop works while I introduced the error about "gps device tracker".

This is because HA see it with 'source_type: gps', **but it's a binary sensor**.

I put here what I see on entity list of develooper tools:

**KEY_TRACKER_ENRICO:**

source_type: gps
latitude: **********
longitude: **********
gps_accuracy: 0
entity_id: binary_sensor.key_tracker_enrico
last_entity_id: binary_sensor.key_tracker_enrico
last_seen: 2020-08-04T15:16:14+02:00
friendly_name: key tracker enrico


**ENRICO_ON_BED**
source_type: binary_sensor
entity_id: binary_sensor.enrico_sleep
last_entity_id: binary_sensor.enrico_sleep
last_seen: 2020-08-04T15:16:10


**ERICA_ON_BED**
source_type: binary_sensor
entity_id: binary_sensor.erica_sleep
last_entity_id: binary_sensor.erica_sleep
last_seen: 2020-08-04T07:16:10+02:00
friendly_name: erica_on_bed

How it is possible? :O 

I hope I have written clearly and sorry for my bad English :)
Thank you again

**Comment by pnbruckner** [comment]
First, when a binary sensor changes to 'on', that is effectively converted to 'home', and it uses HA's GPS location configuration data and converts the source_type to gps so that the device tracker component level code with use the gps data. That is how this has worked since I added support for binary sensors. This is nothing new.

When a binary sensor changes to 'off', whether or not that change is used depends on whether or not gps based trackers have been used yet. If not, then that will effectively be changed to 'not_home'. But it also sets source_type to binary_sensor, which it probably should never have done. Again, the component level device tracker code will not know what to do with that. It should probably use "router" in that case.

Regardless of the above, why do you say it's not working? I still don't understand that. When the binary sensor changes to 'on' does the composite change to 'home', and when the binary sensor changes to 'off' (and the gps based tracker has not yet updated) does the composite change to 'not_home'? If so, then it's working as expected.

**Comment by Gobolin80** [comment]
Ahhh ... ok!
Now I understand how this component works.
How I said above, it didn't work for my mistake (bad configuration of "Zone").
After I corrected the problem also you component restarted to work fine.
If you tell me that this is the normal behavior is all ok.
I never noticed it.

Thanks for all and sorry for disturbing!
