### ISSUE TITLE
Add consider_home option

### ISSUE THREAD

**Issue by badewanne1234** [pnbruckner/ha-composite-tracker#44]
Hi

From reading the docs of this integration, I cannot see an option to add a `consider_home` time (for example 180 seconds). I know it could be done when using automations, however, the built-in device tracker integration of HA offers exactly that.

I have been using the HA integrated device_tracker integration, however since the Unify Router integration does not seem to be reliable anymore, I'm looking for new options, without rewriting all my automations :)

Thanks

**Comment by pnbruckner** [comment]
`consider_home` isn't really something that fits the design of the composite tracker integration.

**Comment by PeaceByPeace** [comment]
> `consider_home` isn't really something that fits the design of the composite tracker integration.

Why? I was hoping to find this option since I'm having the issues with creating device tracker for my ble I beacon from esp32 which in turn is analyzed with binary_sensor and then I could use your integration to make this binary_sensor a device_tracker, so I would be truly glad if you could add something like that

**Comment by pnbruckner** [comment]
@PeaceByPeace, the composite integration, in general, bases its output on whichever input has the "latest data". For non-GPS inputs, however, by default, it only uses their state when they change to "`home`", since these types of inputs are often good at detecting when the device comes home, but are terrible at knowing when it leaves home. However, that can be overridden with the `all_states` option.

It's not really composite's job to figure out if an input is providing good data (beyond what I described above.) Therefore, it has no use for a `consider_home` option. That is really for the input entity's integration, and in general, it is a poor algorithm for compensating for the integration's lack of ability to know when the device leaves home.

Having said all that, the composite does accept `binary_sensor` entities as input. So why can't you use it (with or without the `all_states` option enabled)?
