### ISSUE TITLE
device_tracker.nothing_phone_1 missing gps attributes

### ISSUE THREAD

**Issue by tjorim** [pnbruckner/ha-composite-tracker#51]
I get the following error in my log and the sensor does not always update correctly.
My phone is using the HA app (thus relies on GPS) but is sending the zones only instead if specific coordinates.

```
This error originated from a custom integration.

Logger: custom_components.composite.device_tracker
Source: custom_components/composite/device_tracker.py:614
Integration: Composite (documentation, issues)
First occurred: 25 October 2023 at 23:27:18 (1 occurrences)
Last logged: 25 October 2023 at 23:27:18

device_tracker.nothing_phone_1 missing gps attributes
```

**Comment by pnbruckner** [comment]
I don't use the HA app, so I don't know how it and the associated `device_tracker` entities work. Can you share the attributes of that entity? (Of course, redact data as necessary.)

**Comment by tjorim** [comment]
The only attribute is `source_type: gps`, the state of the entity is the zone id. Here are the two entities I use:
![image](https://github.com/pnbruckner/ha-composite-tracker/assets/1294876/7384ec33-8215-442f-8d2a-eb202e38572b)
First one is from nmap, the second on is from the Android app.

**Comment by pnbruckner** [comment]
Well, it would seem the app isn't working correctly or isn't configured correctly? If its `source_type` is `gps`, then the way I understand it, it is _supposed_ to also provide `latitude`, `longitude` and `gps_accuracy` attributes, which it isn't. That's why the composite integration is outputting an error.

You should ask for help with the Android mobile app to find out why yours isn't producing the expected attributes.

**Comment by tjorim** [comment]
It's supposed to work like that afaik: https://companion.home-assistant.io/docs/core/location/#manage-location-tracking-level

**Comment by pnbruckner** [comment]
Ok, then if you want to use it with the composite integration, you need to set it to Exact.

**Comment by tjorim** [comment]
That's not an option considering privacy, thanks for the help.
