### ISSUE TITLE
Add support for device_tracker.see action

### ISSUE THREAD

**Issue by nzrutman** [pnbruckner/ha-composite-tracker#83]
Would it be possible to add support for the [device_tracker.see action](https://www.home-assistant.io/integrations/device_tracker/#device_trackersee-action) to the composite sensor? This would allow setting of the location via automations, e.g. if my activity sensor says I'm biking, set my location to not_home.

**Comment by nzrutman** [comment]
To be clear, my activity sensor is not a GPS or binary sensor, so can't use it directly by composite tracker. Options:
-  could set up a template binary sensor. But I can't assign a named location this way (eg. location: "Biking").
-  could set up a new device_tracker, and add it to my composite's list. But composite expects the gps type (i.e. any created device_trackers) to have valid GPS coordinates, which my sensor does not have. So I have to set fake GPS coordinates at a position somewhere that I label "Biking". (This is in fact what I have done.)

Not an impossible situation to be sure, but it would be a little more elegant to just set the composite's location directly from my automation with device_tracker.see.

**Comment by pnbruckner** [comment]
Do you want the state to be `not_home` (aka, Away), or the state of your sensor (e.g., `Biking`)? The former, which your first post implied, could be done via the first option in you second post (i.e., a template binary sensor.) The latter, as you say, is not directly supported by the composite integration.

It couldn't be the `device_tracker.see` service, because that is handled by the device tracker component level code and only supports "legacy" trackers, which the composite is not.

It potentially could be done by adding a `composite.xxx` service, but I'm not sure how that would work with the current implementation. Basically, if any input entity changes and has newer data than what the composite has been using, it will update the state of the composite tracker, effectively overwriting any temporary state set via some new service.

Your best bet might be to use the composite _without_ this sensor as input, and then use the composite tracker and the activity sensor in an automation to create a different (legacy) tracker via the `device_tracker.see` service.

**Comment by nzrutman** [comment]
> It potentially could be done by adding a composite.xxx service, ... if any input entity changes and has newer data than what the composite has been using, it will update the state of the composite tracker, effectively overwriting any temporary state set

This is exactly what I would expect - `composite.see` would temporarily set state or attributes of the composite tracker, which would be overwritten by any subsequent updates from another composite input. Same is true for creating a new device_tracker and adding it to composite's list. Just saves me the creation of a new tracker (with the extra efforts noted above - fake gps, etc). So it's just a cleaner, easier way of doing what I'm trying to accomplish in my second bullet.

(You're right, if I wanted my automation to permanently/generally override the composite, I could use composite as an input - but that's not my goal.)

Clearly, there are multiple ways around this problem, and maybe my use case is too much of a snowflake to spend code effort on. Closing to take it off your issues list, thanks for the response (and the integration!)
